GE76:
  tf:
    - /tf
    - /tf_static
  clock:
    - /clock
  wvn:
    - /twist_mux/twist
    - /wild_visual_navigation_node/robot_state
  image:
    - /alphasense_driver_ros/cam3/color/image/compressed
    - /alphasense_driver_ros/cam3/color_rect/image/compressed
    - /alphasense_driver_ros/cam3/color_rect/camera_info
    - /alphasense_driver_ros/cam3/color/camera_info

    - /alphasense_driver_ros/cam4/color/image/compressed
    - /alphasense_driver_ros/cam4/color_rect/image/compressed
    - /alphasense_driver_ros/cam4/color_rect/camera_info
    - /alphasense_driver_ros/cam4/color/camera_info

    - /alphasense_driver_ros/cam5/color/image/compressed
    - /alphasense_driver_ros/cam5/color_rect/image/compressed
    - /alphasense_driver_ros/cam5/color_rect/camera_info
    - /alphasense_driver_ros/cam5/color/camera_info
  imu:
    - /alphasense_driver_ros/imu
    - /sensors/imu
  state_estimation:
    - /state_estimator/odometry
    - /state_estimator/pose_in_odom
    - /joint_states