# TODO split into three configuration files - shared - learning - feature_extractor

# Input topics
robot_state_topic: "/wild_visual_navigation_node/robot_state"
desired_twist_topic: "/twist_mux/twist"

# Relevant frames
fixed_frame: odom
base_frame: base
footprint_frame: footprint

# Robot size
robot_length: 0.8
robot_width: 0.3
robot_height: 0.3


# Traversability estimation params
traversability_radius: 3.0 # meters
image_graph_dist_thr: 0.2 # meters
supervision_graph_dist_thr: 0.1 # meters
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448
segmentation_type: "stego" # Options: slic, grid, random, stego
feature_type: "stego" # Options: dino, dinov2, stego
dino_patch_size: 8 # 8 or 16; 8 is finer
dino_backbone: vit_small
slic_num_components: 100
confidence_std_factor: 4.0

min_samples_for_training: 5
prediction_per_pixel: True
vis_node_index: 10

# Supervision Generator
untraversable_thr: 0.01
mission_name: "test"
mission_timestamp: True

# Threads
image_callback_rate: 10 # hertz
supervision_callback_rate: 10 # hertz
learning_thread_rate: 10 # hertz
logging_thread_rate: 2 # hertz
status_thread_rate: 0.5 # hertz
load_save_checkpoint_rate: 0.2 # hertz, 1/0.2 = 5 sec equivalent

# Runtime options
device: "cuda"
mode: "online" # check out comments in the class WVNMode
colormap: "RdYlBu"

print_image_callback_time: false
print_supervision_callback_time: false
log_time: false
log_confidence: false
verbose: true

extraction_store_folder:  "nan"
exp: "nan"

# TODO: What do we add here for sim or for rosbags? 
# camera_topics:
#   front:
#     image_topic: "/wide_angle_camera_front/image_color_resize"
#     info_topic: "/wide_angle_camera_front_resize/camera_info"
#     use_for_training: true
#     publish_confidence: true
#     publish_input_image: true
#     scheduler_weight: 1
#   rear:
#     image_topic: "/wide_angle_camera_rear/image_color_resize"
#     info_topic: "/wide_angle_camera_rear_resize/camera_info"
#     use_for_training: false
#     publish_confidence: true
#     publish_input_image: true
#     scheduler_weight: 1

# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448