version: "3.9"
services:
  wvn:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    volumes:
      - ../../wild_visual_navigation:/root/catkin_ws/src/wild_visual_navigation
    command: '/bin/bash'